export const FETCH_PRODUCT_LIST_SUCCESS = 'FETCH_PRODUCT_LIST_SUCCESS'
export const FETCH_PRODUCT_DEATAILS_SUCCESS = 'FETCH_PRODUCT_DEATAILS_SUCCESS'
export const FETCH_PRODUCT_ADDED_TO_CART_SUCCESS =
  'FETCH_PRODUCT_ADDED_TO_CART_SUCCESS'
